### ISSUE TITLE
Support for bosco, xevious on the Galaga driver

### ISSUE THREAD

**Issue by arnoldsecret** [dinkc64/FBAlphaFB#4]
These games are the only Namco classics that are left unsupported, we already have the drivers needed, so porting is an easy task.

**Comment by dinkc64** [comment]
They are definitely on the todo list.

Due to the fact they need a completely different video, loader, inputs/prot, adding them to the existing driver will be just as difficult as creating a whole new driver.  But if you think that is easy, feel free to add them :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
@CupcakeFan added xevious support to the old fbalpha libretro port in https://github.com/libretro/fbalpha/pull/230 , i asked him to port his work here.

**Comment by CupcakeFan** [comment]
Yessir, forking and porting right away.

**Comment by dinkc64** [comment]
CupcakeFan, AWESOME!! :)

**Comment by arnoldsecret** [comment]
now if you could get bosconian on here, that would be better

**Comment by dinkc64** [comment]
It's already great that he added Xevious - did you see all the work he did? :)

**Comment by arcadez** [comment]
Some folks are harder to please me im over the proverbial moon ;)

**Comment by arnoldsecret** [comment]
well it's time to close this, we'll welcome our first post-FBA addition into the library of great games for this emu.

**Comment by dinkc64** [comment]
@CupcakeFan I added to the main fb git and did a couple of changes, hope you don't mind :)
https://github.com/dinkc64/FBAlphaFB/commit/dafe1cf94fa8199563d197bb0dfe48b4466a4842

please read the comment for a list of what I had changed from your version :)

**Comment by CupcakeFan** [comment]
Thanks for the help, and the improvements. :)
