### ISSUE TITLE
Wrong crc32 of bk3e (md)

### ISSUE THREAD

**Issue by okurka** [dinkc64/FBAlphaFB#6]
The crc32 of MegaDrive rom bare knuckle iii (english translation).bin should be 68917751 instead of 041b99f7.

Or was there a newer translation than Twilight v1.0?

**Comment by dinkc64** [comment]
Thank you, 0x68917751 is right - it looks like a typo caused it to be in decimal form instead of hexidecimal.

**Comment by Ryvius86** [comment]
That's my fault. I used 7zip to check the CRC, not realising it was converted to decimal. Thanks.
